### ISSUE TITLE
Ability to keep an proxy using an "request hash"

### ISSUE THREAD

**Issue by pedrommone** [pedrommone/araneo#60]
### The problem

I'm thinking in something to keep a proxy between sessions.

The main problem today is that we ask for a new proxy on every request. This can be a problem when crawling, because the crawlers can "fire" an IP address when rotating the same "authorization keep" with different IP addresses.

####  Request ID approach

When requesting a proxy, we should generate an unique id and attach it to a proxy. When the consumer want to keep the proxy, then, he should pass the id as header. When he wants a brand new request, just dont pass the unique id.

#### Request idempotency signature approach

The  consumer should generate and random hash and we shall attach it to a proxy. The renew/keep process should be the same as the approach above.

**Comment by DennyLoko** [comment]
The request to get a new proxy should be idempotent, that is, the consumer should specify a `X-Idempotency` header with a random string, and every time that same string is received by the API it should answer with the same proxy.

This way, the session management isn't handled by the system, but the consumer, which could implement any sessions management it wants.
